SELECT Phong, COUNT(MaNV) AS SL_NHÂNVIÊN
FROM NHANVIEN AS NV, (SELECT Phong AS MaPB
					  FROM NHANVIEN
					  GROUP BY Phong
					  HAVING COUNT(MaNV) > 2) BUF
WHERE MaPB = NV.Phong AND NV.Luong > 25000
GROUP BY Phong