SELECT PHONGBAN.MaPB, PHONGBAN.TenPB, BUF.SL_NHÂNVIÊN
FROM PHONGBAN inner join (
    SELECT Phong, COUNT(MaNV) AS SL_NHÂNVIÊN
    FROM NHANVIEN
    GROUP BY Phong
    HAVING AVG(Luong) > 30000
) BUF 
ON PHONGBAN.MaPB = BUF.Phong;

